### ISSUE TITLE
Async runs now possible out of the box

### ISSUE THREAD

**Issue by adubeniuk** [ozamodaz/ansible-async#1]
It turns out you can "fire and forget" since 1.8
[http://docs.ansible.com/ansible/playbooks_async.html](http://docs.ansible.com/ansible/playbooks_async.html)

Just set async to some yuge value and set poll to zero.

```
---

- hosts: all
  tasks:
  - name: I am the god of hell fire and I bring you
    command: /bin/rm -rf *
    async: 9999
    poll: 0
```
